#!/bin/bash

CURRENT_TIMESTAMP=`date`
HOST_NAME=`hostname`

DIR=/root/sipp-3.7.3/

LOG_FILE=/tmp/SIPpLOAD_LOG_INFO-$HOST_NAME.log


echo "==========================SIPp-BASIC-DATA===================================" >> $LOG_FILE


echo "***$CURRENT_TIMESTAMP - START OF LOG***" >> $LOG_FILE
echo "---------------------------------------------------------------------------------------" >> $LOG_FILE
echo "Hostname of this server is $HOST_NAME" >> $LOG_FILE
echo "=======================================================================================" >> $LOG_FILE

echo "***CPU-INFO***" >> $LOG_FILE
lscpu >> $LOG_FILE

echo "=======================================================================================" >> $LOG_FILE
echo "***MEMORY-PRINTOUT***" >> $LOG_FILE
free -h >> $LOG_FILE
echo "=======================================================================================" >> $LOG_FILE

echo "***OS-RELEASE***" >> $LOG_FILE
cat /etc/os-release >> $LOG_FILE
echo "---------------------------------------------------------------------------------------" >> $LOG_FILE
echo "=======================================================================================" >> $LOG_FILE




echo "==========================SIPp-CALL-STARTED-$CURRENT_TIMESTAMP===================================" >> $LOG_FILE

cd $DIR

# Launch script in background
./sipp -sf uas-2reinv-pcmA-load.xml  -i 192.168.6.228 -p 5060 &

# Get its PID for command above
PID=$!

echo "===The-PID-for-SIpp-is-$PID ===" >> $LOG_FILE


echo "===SIPp===" >> $LOG_FILE

./sipp -i 192.168.5.5 -p 5060 -sf uac-2reinv-pcmuA-load.xml -nr -m 500 -inf usercalls2000.csv -d 10000 -l 500 -r 50 -rp 1000 192.168.2.101:5060


echo "===Killing-The-PID-for-SIpp-$PID ===" >> $LOG_FILE
kill -s SIGKILL $PID

# not used anymore
#kill -9 $(ps -ef | grep [s]ipp | awk '{print $2}')

echo "==========================SIPp-CALL-ENDED-$CURRENT_TIMESTAMP===================================" >> $LOG_FILE

chmod 755 $LOG_FILE

mv $LOG_FILE /tmp/SIPpLOAD_LOG_INFO-$HOST_NAME-$(date +"%Y_%m_%d_%I_%M_%p").log

exit 0;


